export type User = { id: string; email: string; fullName: string };
export type HealthProfile = {
  id: string;
  displayName?: string;
  display_name?: string;
  birthDate?: string | null;
  birth_date?: string | null;
  relationship: 'SELF' | 'CHILD' | 'PARENT' | 'OTHER';
  notes?: string | null;
};
export type EventType = 'ANTECEDENT' | 'CONSULTATION' | 'DIAGNOSIS' | 'TREATMENT' | 'MEDICATION' | 'ALLERGY' | 'VACCINE' | 'SURGERY' | 'LAB_RESULT' | 'SYMPTOM' | 'OTHER';
export type HealthEvent = {
  id: string;
  profileId?: string;
  profile_id?: string;
  eventType?: EventType;
  event_type?: EventType;
  title: string;
  description?: string | null;
  eventDate?: string;
  event_date?: string;
  source?: string | null;
  notes?: string | null;
  details?: Record<string, unknown> | null;
  documents?: ClinicalDocument[];
};
export type ClinicalDocument = {
  id: string;
  eventId?: string | null;
  event_id?: string | null;
  originalName?: string;
  original_name?: string;
  mimeType?: string;
  mime_type?: string;
  sizeBytes?: number;
  size_bytes?: number;
  createdAt?: string;
  created_at?: string;
};
export type PagedEvents = { items: HealthEvent[]; page: number; pageSize: number; total: number; totalPages: number };
export type AiResult = {
  id: string;
  provider: string;
  model: string;
  summary: string;
  incompleteData: string[];
  contradictions: string[];
  questions: string[];
  disclaimer: string;
};
export type SymptomRecurrence = { symptomName: string; occurrences: number; firstRecordedAt: string; lastRecordedAt: string; activeOccurrences: number };
export type MedicationDoseSlot = { scheduledDate: string; scheduledTime: string };
export type MedicationAdherence = { confirmed: number; total: number; missed: number; percentage: number; pending: MedicationDoseSlot[] };
export type MedicationRegimen = {
  id: string;
  profileId: string;
  medicationName: string;
  dose?: string | null;
  scheduleDays: number[];
  scheduleTimes: string[];
  startDate: string;
  endDate?: string | null;
  notes?: string | null;
  isActive: boolean;
  adherence: MedicationAdherence;
};
export type PlanCode = 'FREE' | 'SILVER' | 'GOLD';
export type SubscriptionPlan = {
  code: PlanCode;
  name: string;
  monthlyPrice: number;
  analysisEveryDays: number;
  weeklyChatLimit: number | null;
  simulated: boolean;
  subscription: {
    status: 'FREE' | 'SIMULATED_ACTIVE' | 'CANCELED';
    activatedAt: string | null;
    currentPeriodStart: string | null;
    currentPeriodEnd: string | null;
    cancelAtPeriodEnd: boolean;
    canceledAt: string | null;
    autoRenews: boolean;
  };
};
export type PlanStatus = {
  plan: SubscriptionPlan;
  consent: { granted: boolean; grantedAt: string | null };
  chat: { usedThisWeek: number; limit: number | null; resetsAt: string };
  analysis: { everyDays: number; lastAnalysisAt: string | null; nextAnalysisAt: string | null; availableNow: boolean };
};
