import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import { env } from './config/env.js';
import { authRouter } from './routes/auth-routes.js';
import { profileRouter } from './routes/profile-routes.js';
import { eventRouter } from './routes/event-routes.js';
import { documentRouter } from './routes/document-routes.js';
import { summaryRouter } from './routes/summary-routes.js';
import { aiRouter } from './routes/ai-routes.js';
import { billingRouter } from './routes/billing-routes.js';
import { notificationRouter } from './routes/notification-routes.js';
import { shareRouter } from './routes/share-routes.js';
import { publicShareRouter } from './routes/public-share-routes.js';
import { errorHandler, notFound } from './middleware/errors.js';

export const app = express();
app.set('trust proxy', 1);
app.disable('x-powered-by');
app.use(helmet({ crossOriginResourcePolicy: { policy: 'cross-origin' } }));
app.use(cors({ origin: env.corsOrigin === '*' ? true : env.corsOrigin.split(',').map((x) => x.trim()), credentials: false }));
app.use(express.json({ limit: '1mb' }));
app.use(express.urlencoded({ extended: false, limit: '1mb' }));

const authLimiter = rateLimit({ windowMs: 15 * 60 * 1000, limit: 80, standardHeaders: 'draft-8', legacyHeaders: false });
const aiLimiter = rateLimit({ windowMs: 15 * 60 * 1000, limit: 40, standardHeaders: 'draft-8', legacyHeaders: false });
app.use('/api/auth', authLimiter, authRouter);

app.get('/health', (_req, res) => res.json({ ok: true, service: 'Clinicsoft API', time: new Date().toISOString() }));
app.use(publicShareRouter);
app.use('/api/profiles', profileRouter);
app.use('/api', eventRouter);
app.use('/api', documentRouter);
app.use('/api', summaryRouter);
app.use('/api/billing', billingRouter);
app.use('/api/notifications', notificationRouter);
app.use('/api', shareRouter);
app.use('/api', aiLimiter, aiRouter);
app.use(notFound);
app.use(errorHandler);
