import React, { useEffect, useState } from 'react';
import { Alert, ScrollView, Text } from 'react-native';
import { apiRequest } from '../api/client';
import { AppTitle, Chip, Field, PrimaryButton, Screen } from '../components/ui';
import { nameOf, useProfiles } from '../context/ProfileContext';
import type { HealthProfile } from '../types/domain';

const relations:Array<{value:HealthProfile['relationship'];label:string}>=[{value:'SELF',label:'Propio'},{value:'CHILD',label:'Hijo/a'},{value:'PARENT',label:'Padre/madre'},{value:'OTHER',label:'Otro dependiente'}];
export function ProfileFormScreen({route,navigation}:any){const{profiles,refreshProfiles}=useProfiles();const profileId=route.params?.profileId as string|undefined;const existing=profiles.find(p=>p.id===profileId);const[displayName,setDisplayName]=useState(existing?nameOf(existing):'');const[birthDate,setBirthDate]=useState(existing?(existing.birthDate||existing.birth_date||''):'');const[relationship,setRelationship]=useState<HealthProfile['relationship']>(existing?.relationship||'CHILD');const[notes,setNotes]=useState(existing?.notes||'');const[loading,setLoading]=useState(false);useEffect(()=>{if(existing){setDisplayName(nameOf(existing));setBirthDate(existing.birthDate||existing.birth_date||'');setRelationship(existing.relationship);setNotes(existing.notes||'');}},[profileId]);async function save(){if(displayName.trim().length<2)return Alert.alert('Falta el nombre','Escribe un nombre para el perfil.');setLoading(true);try{const body={displayName:displayName.trim(),birthDate:birthDate||null,relationship,notes:notes||null};if(profileId)await apiRequest(`/profiles/${profileId}`,{method:'PATCH',body:JSON.stringify(body)});else await apiRequest('/profiles',{method:'POST',body:JSON.stringify(body)});await refreshProfiles();navigation.goBack();}catch(e:any){Alert.alert('No se pudo guardar',e.message);}finally{setLoading(false);}}return <Screen><AppTitle title={profileId?'Editar perfil':'Nuevo perfil'} subtitle="Los perfiles dependientes se administran desde la cuenta del representante."/><Field label="Nombre visible" value={displayName} onChangeText={setDisplayName}/><Field label="Fecha de nacimiento (AAAA-MM-DD)" value={birthDate} onChangeText={setBirthDate}/><Text style={{fontWeight:'800',marginBottom:8}}>Relación</Text><ScrollView horizontal showsHorizontalScrollIndicator={false}>{relations.filter(r=>existing?.relationship==='SELF'?r.value==='SELF':r.value!=='SELF').map(r=><Chip key={r.value} label={r.label} selected={relationship===r.value} onPress={()=>setRelationship(r.value)}/>)}</ScrollView><Field label="Notas del perfil" value={notes} onChangeText={setNotes} multiline/><PrimaryButton title="Guardar perfil" onPress={save} loading={loading}/></Screen>}
