import React, { useCallback } from 'react';
import { Alert, Pressable, Text, View } from 'react-native';
import { useFocusEffect } from '@react-navigation/native';
import { apiRequest } from '../api/client';
import { AppTitle, Card, Muted, PrimaryButton, Screen, SecondaryButton } from '../components/ui';
import { nameOf, useProfiles } from '../context/ProfileContext';
import { colors } from '../theme/colors';

const relation:Record<string,string>={SELF:'Perfil principal',CHILD:'Dependiente: hijo/a',PARENT:'Dependiente: padre/madre',OTHER:'Dependiente / otro'};
export function ProfilesScreen({navigation}:any){const{profiles,selectedProfile,selectProfile,refreshProfiles}=useProfiles();useFocusEffect(useCallback(()=>{refreshProfiles();},[]));async function remove(id:string){Alert.alert('Eliminar perfil dependiente','Se eliminarán sus eventos, análisis y documentos. Esta acción no se puede deshacer.',[{text:'Cancelar',style:'cancel'},{text:'Eliminar',style:'destructive',onPress:async()=>{try{await apiRequest(`/profiles/${id}`,{method:'DELETE'});await refreshProfiles();}catch(e:any){Alert.alert('No se pudo eliminar',e.message);}}}]);}return <Screen><AppTitle title="Perfiles" subtitle="Administra tu registro principal y perfiles dependientes bajo tu cuenta."/><PrimaryButton title="+ Crear perfil dependiente" onPress={()=>navigation.navigate('ProfileForm')}/>{profiles.map(p=><Card key={p.id} style={{borderColor:selectedProfile?.id===p.id?colors.primary:colors.border}}><Pressable onPress={()=>selectProfile(p.id)}><View style={{flexDirection:'row',justifyContent:'space-between',gap:10}}><View style={{flex:1}}><Text style={{fontSize:17,fontWeight:'800',color:colors.text}}>{nameOf(p)}</Text><Muted>{relation[p.relationship]||p.relationship}{(p.birthDate||p.birth_date)?` · Nacimiento ${p.birthDate||p.birth_date}`:''}</Muted></View>{selectedProfile?.id===p.id?<Text style={{color:colors.primary,fontWeight:'900'}}>ACTIVO</Text>:null}</View></Pressable><SecondaryButton title="Editar" onPress={()=>navigation.navigate('ProfileForm',{profileId:p.id})}/>{p.relationship!=='SELF'?<SecondaryButton title="Eliminar perfil" onPress={()=>remove(p.id)}/>:null}</Card>)}</Screen>}
