import React, { useCallback, useState } from 'react';
import { Alert, Text, View } from 'react-native';
import { useFocusEffect } from '@react-navigation/native';
import { apiRequest } from '../api/client';
import { AppTitle, Card, Muted, Screen, SectionTitle } from '../components/ui';
import { useProfiles } from '../context/ProfileContext';
import { colors } from '../theme/colors';

type Summary={generatedAt:string;profile:any;allergies:any[];medications:any[];diagnoses:any[];antecedents:any[];surgeries:any[];vaccines:any[];recentLabs:any[];notice:string};
function Block({title,items,render}:{title:string;items:any[];render:(x:any)=>string}){return <><SectionTitle>{title}</SectionTitle><Card>{items.length?items.map((x,i)=><View key={x.id||i} style={{marginBottom:10}}><Text style={{fontWeight:'800',color:colors.text}}>{render(x)}</Text><Muted>{x.eventDate||''}</Muted></View>):<Muted>Sin registros en esta sección.</Muted>}</Card></>}
export function SummaryScreen(){const{selectedProfile}=useProfiles();const[data,setData]=useState<Summary|null>(null);const load=useCallback(()=>{if(!selectedProfile)return;apiRequest<Summary>(`/profiles/${selectedProfile.id}/consultation-summary`).then(setData).catch((e:any)=>Alert.alert('Error',e.message));},[selectedProfile?.id]);useFocusEffect(useCallback(()=>{load();},[load]));if(!data)return <Screen><Muted>Preparando vista estructurada…</Muted></Screen>;return <Screen><AppTitle title="Resumen para consulta" subtitle="Vista estructurada creada directamente desde los datos registrados, sin IA."/><Card style={{backgroundColor:'#EEF8F8'}}><Text style={{fontWeight:'900',color:colors.primary}}>{data.profile.displayName}</Text><Muted>Generado: {new Date(data.generatedAt).toLocaleString()}</Muted><Text style={{marginTop:10,color:colors.text,lineHeight:20}}>{data.notice}</Text></Card><Block title="Alergias" items={data.allergies} render={x=>`${x.allergen||x.title}${x.reaction?` — ${x.reaction}`:''}`}/><Block title="Medicamentos" items={data.medications} render={x=>`${x.medicationName||x.title}${x.dose?` · ${x.dose}`:''}${x.frequency?` · ${x.frequency}`:''}`}/><Block title="Diagnósticos declarados" items={data.diagnoses} render={x=>x.diagnosisName||x.title}/><Block title="Antecedentes" items={data.antecedents} render={x=>x.conditionName||x.title}/><Block title="Cirugías" items={data.surgeries} render={x=>x.procedureName||x.title}/><Block title="Vacunas" items={data.vaccines} render={x=>`${x.vaccineName||x.title}${x.doseNumber?` · dosis ${x.doseNumber}`:''}`}/><Block title="Resultados recientes" items={data.recentLabs} render={x=>`${x.testName||x.title}: ${x.valueText??x.valueNumeric??'sin valor'} ${x.unit||''}`}/></Screen>}
